name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Gradle
        run: ./gradlew bootWar

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Deploy WAR to EC2
        run: |
          scp -o StrictHostKeyChecking=no \
              build/libs/app.war \
              ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/

      - name: Restart Tomcat
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} \
           ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          sudo systemctl restart myapp.service
          EOF